const KEY_LIST = {
  GOOGLE_API_KEY: "AIzaSyAQ9wct1-vxk1y90LYLT6Ow1CxTU0b-E5c",
  CONST: {
    LOGIN_USER: "LUT",
    LOGIN_TOKEN: "LUT_TK",
    PLAY_INFO: "PLAY_INFO",
    CHANGE_LANG: "CHANGE_LANG",
  },
};
export { KEY_LIST };
